[package]
name = "fox-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fox-core = { path = "../fox-core" }
fox-sign = { path = "../fox-sign" }
url = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }