//! HTML 离线单页文档导出。
//!
//! 生成零依赖的静态单文件（内联样式、无脚本）：深色主题卡片式排版，
//! 每个接口一张卡（Method 徽标 + 路径 + 描述 + 参数表 + Body / 响应示例），
//! 可直接发给前端 / 测试同学离线浏览。

use std::collections::HashMap;
use std::fmt::Write as _;

use uuid::Uuid;

use fox_core::model::{AuthSpec, BodySpec, Endpoint, KeyValue, ResponseExample};

/// 将一组接口导出为离线 HTML 文档。
pub fn export_html(
    project_name: &str,
    endpoints: &[Endpoint],
    examples_by_endpoint: &HashMap<Uuid, Vec<ResponseExample>>,
) -> String {
    let mut cards = String::with_capacity(8192);
    for (idx, ep) in endpoints.iter().enumerate() {
        let empty: Vec<ResponseExample> = Vec::new();
        let examples = examples_by_endpoint.get(&ep.id).unwrap_or(&empty);
        let _ = write_card(&mut cards, idx + 1, ep, examples);
    }

    format!(
        "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>{project_name} · API 文档</title>\n<style>{CSS}</style>\n</head>\n<body>\n\
         <header class=\"page-head\"><h1>{project_name}</h1>\
         <p class=\"meta\">API 文档 · 由 RustFox 导出 · 共 {count} 个接口</p></header>\n\
         <main>{cards}</main>\n\
         <footer class=\"page-foot\">Generated by RustFox</footer>\n\
         </body>\n</html>\n",
        project_name = escape(project_name),
        count = endpoints.len(),
        cards = cards,
        CSS = CSS,
    )
}

/// 拼写单个接口卡片。
fn write_card(
    out: &mut String,
    index: usize,
    ep: &Endpoint,
    examples: &[ResponseExample],
) -> std::fmt::Result {
    let method = ep.method.as_str().to_lowercase();
    let title = if ep.name.is_empty() {
        "未命名接口".to_string()
    } else {
        escape(&ep.name)
    };
    writeln!(
        out,
        "<section class=\"card\">\
         <div class=\"card-head\"><span class=\"method m-{method}\">{}</span>\
         <code class=\"path\">{}</code><h2>{title}</h2><span class=\"idx\">#{index}</span></div>",
        escape(ep.method.as_str()),
        escape(&ep.path),
        method = method,
        index = index,
    )?;

    if !ep.description.is_empty() {
        writeln!(out, "<p class=\"desc\">{}</p>", escape(&ep.description))?;
    }

    let auth = auth_line(&ep.request.auth);
    if !auth.is_empty() {
        write!(out, "<p class=\"kv-line\"><b>认证</b>{auth}</p>")?;
    }

    kv_table(out, "Query 参数", &ep.request.params)?;
    kv_table(out, "请求头", &ep.request.headers)?;

    match &ep.request.body {
        BodySpec::Json { raw } if !raw.trim().is_empty() => {
            block(out, "请求 Body (JSON)", raw)?;
        }
        BodySpec::Text { raw } if !raw.trim().is_empty() => block(out, "请求 Body (Text)", raw)?,
        BodySpec::UrlEncoded { fields } => kv_table(out, "请求 Body (Form)", fields)?,
        _ => {}
    }

    for ex in examples {
        let label = format!("响应示例 {} {}", ex.status, escape(&ex.name));
        block(out, &label, &ex.body)?;
    }

    writeln!(out, "</section>")
}

fn kv_table(out: &mut String, title: &str, list: &[KeyValue]) -> std::fmt::Result {
    let rows: Vec<&KeyValue> = list
        .iter()
        .filter(|kv| kv.enabled && !kv.key.trim().is_empty())
        .collect();
    if rows.is_empty() {
        return Ok(());
    }
    writeln!(
        out,
        "<h3>{title}</h3><table><thead><tr><th>名称</th><th>值 / 示例</th><th>说明</th></tr></thead><tbody>"
    )?;
    for kv in rows {
        let value = if kv.example.is_empty() {
            &kv.value
        } else {
            &kv.example
        };
        writeln!(
            out,
            "<tr><td><code>{}</code></td><td><code>{}</code></td><td>{}</td></tr>",
            escape(&kv.key),
            escape(value),
            escape(&kv.description),
        )?;
    }
    writeln!(out, "</tbody></table>")
}

fn block(out: &mut String, title: &str, body: &str) -> std::fmt::Result {
    writeln!(out, "<h3>{}</h3><pre>{}</pre>", escape(title), escape(body))
}

fn auth_line(auth: &AuthSpec) -> String {
    match auth {
        AuthSpec::None => String::new(),
        AuthSpec::Bearer { .. } => "Bearer Token（Authorization 头）".into(),
        AuthSpec::Basic { .. } => "Basic Auth".into(),
        AuthSpec::ApiKey { key, location, .. } => {
            format!(
                "API Key：{key}（{}）",
                if *location == fox_core::model::ApiKeyLocation::Header {
                    "Header"
                } else {
                    "Query"
                }
            )
        }
        AuthSpec::OAuth2 { .. } => "OAuth2".into(),
        AuthSpec::Digest { .. } => "Digest 认证（RFC 7616）".into(),
        AuthSpec::Hawk { .. } => "Hawk 认证（HMAC-SHA-256）".into(),
        AuthSpec::AwsV4 { .. } => "AWS Signature V4".into(),
        AuthSpec::Hmac { .. } => "HMAC (AK-SK)".into(),
        AuthSpec::DynamicSignature { config } => {
            format!(
                "动态签名：Key {}，{:?}/{:?}，签名头 {}",
                config.app_key, config.algorithm, config.encoding, config.sig_header
            )
        }
    }
}

/// 极简 HTML 转义（文档内容均来自用户数据）。
fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const CSS: &str = r#"
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; padding: 32px 20px 60px; background: #0c0c0d; color: #e7e7ea;
       font: 14px/1.7 -apple-system, "PingFang SC", "Segoe UI", sans-serif; }
main, header.page-head, footer.page-foot { max-width: 880px; margin: 0 auto; }
h1 { font-size: 26px; margin: 0 0 6px; }
.meta { color: #9a9aa3; margin: 0 0 28px; font-size: 13px; }
.card { background: #161618; border: 1px solid #232326; border-radius: 12px;
        padding: 18px 20px; margin-bottom: 18px; }
.card-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.card-head h2 { font-size: 16px; margin: 0; }
.idx { margin-left: auto; color: #62626b; font-size: 12px; }
.method { font-family: ui-monospace, monospace; font-weight: 700; font-size: 12px;
          padding: 2px 10px; border-radius: 6px; }
.m-get  { color: #34d399; background: rgba(16,185,129,.12); }
.m-post { color: #fbbf24; background: rgba(245,158,11,.12); }
.m-put  { color: #60a5fa; background: rgba(59,130,246,.12); }
.m-patch{ color: #a78bfa; background: rgba(167,139,250,.14); }
.m-delete { color: #fb7185; background: rgba(239,68,68,.12); }
.path { font-family: ui-monospace, monospace; font-size: 14px; color: #e7e7ea;
        word-break: break-all; }
.desc { color: #9a9aa3; margin: 10px 0 0; white-space: pre-wrap; }
.kv-line { color: #9a9aa3; } .kv-line b { color: #62626b; font-weight: 600; margin-right: 8px; }
h3 { font-size: 12px; text-transform: uppercase; letter-spacing: .06em;
     color: #62626b; margin: 20px 0 8px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #232326; }
th { color: #a3a3a3; font-weight: 600; font-size: 12px; }
code { font-family: ui-monospace, monospace; font-size: 12.5px; color: #c8c8d0; }
pre { background: #101012; border: 1px solid #232326; border-radius: 8px;
      padding: 12px 14px; overflow-x: auto; font-family: ui-monospace, monospace;
      font-size: 12.5px; line-height: 1.6; margin: 0; }
footer.page-foot { margin-top: 36px; color: #62626b; font-size: 12px; text-align: center; }
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use fox_core::model::{EndpointStatus, HttpMethod, RequestSpec};

    fn sample() -> Endpoint {
        Endpoint {
            id: Uuid::new_v4(),
            project_id: Uuid::new_v4(),
            folder_id: None,
            name: "查询用户 <v2>".into(),
            method: HttpMethod::GET,
            path: "/api/v1/users/{id}".into(),
            description: "分页查询 & 过滤".into(),
            status: EndpointStatus::Released,
            sort_order: 0,
            request: RequestSpec {
                params: vec![KeyValue {
                    key: "page".into(),
                    value: "1".into(),
                    enabled: true,
                    description: "页码".into(),
                    field_type: Default::default(),
                    required: true,
                    example: String::new(),
                }],
                ..RequestSpec::default()
            },
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn html_contains_escaped_cards() {
        let mut examples = HashMap::new();
        let ep = sample();
        examples.insert(
            ep.id,
            vec![ResponseExample {
                id: Uuid::new_v4(),
                endpoint_id: ep.id,
                name: "成功".into(),
                status: 200,
                headers: Default::default(),
                body: "{\"ok\":true}".into(),
                content_type: "application/json".into(),
                created_at: Utc::now(),
                updated_at: Utc::now(),
            }],
        );

        let html = export_html("演示&项目", &[ep], &examples);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("演示&amp;项目")); // 标题转义
        assert!(html.contains("查询用户 &lt;v2&gt;"));
        assert!(html.contains("分页查询 &amp; 过滤"));
        assert!(html.contains("<code>page</code>"));
        // 引号被转义为 &quot;（escape 后的 JSON 文本）
        assert!(html.contains("{&quot;ok&quot;:true}"));
        assert!(html.contains("m-get"));
        // 无脚本：纯静态离线文档
        assert!(!html.contains("<script"));
    }

    #[test]
    fn disabled_params_excluded() {
        let mut ep = sample();
        ep.request.params[0].enabled = false;
        let html = export_html("P", &[ep], &HashMap::new());
        assert!(!html.contains(">page<"));
    }
}
