[package]
name = "fox-mock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fox-core = { path = "../fox-core" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }