[package]
name = "fox-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fox-core = { path = "../fox-core" }
fox-sign = { path = "../fox-sign" }
fox-storage = { path = "../fox-storage" }
fox-oauth = { path = "../fox-oauth" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
base64 = { workspace = true }
md-5 = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
serde_urlencoded = { workspace = true }
bytes = { workspace = true }
url = { workspace = true }
sqlx = { workspace = true }
rquickjs = { workspace = true }
tokio-tungstenite = { workspace = true }